"""Merged results table: cells and contrasts for every decoder, from the run CSVs."""
import csv
from collections import defaultdict
from pathlib import Path
import numpy as np

HERE = Path(__file__).resolve().parent
TEX = HERE.parent / "paper" / "tables" / "table_main.tex"
LABEL = {"linear_frozen": "Linear (primary)", "centroid_frozen": "Cosine centroid",
         "mlp": "MLP (512 hidden)", "knn": "Cosine $k$-NN"}
ORDER = ["linear_frozen", "centroid_frozen", "mlp", "knn"]
CELLS = ("D", "A", "B", "C")

rows = list(csv.DictReader((HERE / "r1_decoder_strength.csv").open()))
agg = defaultdict(lambda: defaultdict(list))
for r in rows:
    for c in CELLS:
        agg[(r["pipeline"], r["readout"])][c].append(float(r[f"macro_f1_{c}"]))
    agg[(r["pipeline"], r["readout"])]["BC"].append(float(r["B_minus_C"]))
    agg[(r["pipeline"], r["readout"])]["BA"].append(float(r["B_minus_A"]))

f = lambda x: f"{x:.3f}"
lines = ["% Generated by revision/make_tables.py from r1_decoder_strength.csv.",
         r"\begin{table*}[t]", r"\centering",
         r"\caption{Cell macro-F1 and the two contrasts under four decoders, "
         r"means over the 12 matched configurations.}",
         r"\label{tab:main}", r"\small", r"\setlength{\tabcolsep}{4.4pt}",
         r"\begin{tabular}{llccccccc}", r"\toprule",
         r"& & \multicolumn{4}{c}{Cell macro-F1 mean} & "
         r"\multicolumn{2}{c}{Contrast mean [min, max]} & Positive configs. \\",
         r"\cmidrule(lr){3-6}\cmidrule(lr){7-8}",
         r"Pipeline & Decoder & D & A & B & C & $B-A$ & $B-C$ & $B-A$; $B-C$ \\",
         r"\midrule"]
for pipe, name in (("birdnet", "BirdNET"), ("perch", "Perch")):
    for i, key in enumerate(ORDER):
        d = agg[(pipe, key)]
        ba, bc = np.array(d["BA"]), np.array(d["BC"])
        lines.append(
            f"{name if i == 0 else ''} & {LABEL[key]} & " +
            " & ".join(f(np.mean(d[c])) for c in CELLS) +
            f" & {f(ba.mean())} [{f(ba.min())}, {f(ba.max())}]"
            f" & {f(bc.mean())} [{f(bc.min())}, {f(bc.max())}]"
            f" & {int((ba > 0).sum())}/12; {int((bc > 0).sum())}/12 \\\\")
    if pipe == "birdnet":
        lines.append(r"\midrule")
lines += [r"\bottomrule", r"\end{tabular}", r"\vspace{1mm}", "",
          r"\begin{minipage}{0.98\textwidth}", r"\small",
          "All decoders share the same training clips and test clips in every "
          "configuration; the linear and centroid rows are the frozen primary and "
          "secondary readouts. Contrast columns give the mean [minimum, maximum] over "
          "configurations, followed by the count of configurations with a positive "
          "contrast.", r"\end{minipage}", r"\end{table*}", ""]
TEX.write_text("\n".join(lines))
print("wrote", TEX)
print("\n".join(lines[13:24]))
